### ISSUE TITLE
this.options 在webpack4中已经移除

### ISSUE THREAD

**Issue by zhouxinyong** [tangjinzhou/vue-antd-md-loader#1]
项目升级到webpack4以后，添加vue-antd-md-loader后报错，源码中用了this.options 以及this.options.vueMarkdown，在webpack4中已经移除了options属性

**Comment by tangjinzhou** [comment]
这个插件目前仅服务于ant-design-vue，暂时没有计划升级webpack4用来构建ant-design-vue，当然欢迎PR

**Comment by zhouxinyong** [comment]
Ok,I will rewrite,thanks!
